version: "3.9"

services:

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: frontend
    tty: true
    stdin_open: true
    volumes:
      - ./frontend/react-app:/app/frontend
    command: sh -c "cd /app/frontend && yarn start"
    ports:
      - 3000:3000

  backend:
    build: 
      context: .
      dockerfile: ./docker/backend/Dockerfile
      args:
        - target=dev
    container_name: backend
    ports:
        - 8000:8000
    tty: true 
    stdin_open: true
    volumes:
      - ./backend:/app/backend
    environment:
      DB_HOST: suggest_laboratory_db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: suggest_laboratory

  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: suggest_laboratory_db
    ports:
      - 3306:3306
    volumes:
      - './db/data:/var/lib/mysql'
      - './db/mysql/conf.d:/etc/mysql/conf.d'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: suggest_laboratory

volumes: 
  suggest_laboratory-data:
